name: 'Handle stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4.1.1
        with:
          days-before-issue-stale: 30
          stale-issue-label: 'stale'

          days-before-pr-stale: 30
          stale-pr-label: 'stale'

          remove-stale-when-updated: true
          debug-only: true
